openapi: 3.0.0
servers:
  - url: 'https://localhost:8877/'
    description: Local Development
    variables: {}
info:
  description: '선린인터넷고등학교 웹앱개발 전공동아리, TAPIE'
  version: 0.0.3
  title: TAPIE API
  termsOfService: ''
  contact:
    email: contact@tapie.kr
    name: TAPIE
    url: https;//tapie.kr
  license:
    name: MIT
    url: 'https://opensource.org/license/mit'
tags:
  - name: Health
    description: Health Checking
paths:
  /:
    get:
      summary: Health Checking
      description: ''
      parameters: [ ]
      operationId: ''
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                status: ok
                availableVersions:
                  - v1
      tags:
        - Health
      security: [ ]
    summary: Health Checking
    description: ''
externalDocs:
  description: 'Bump.sh Docs'
  url: 'https://docs.tapie.kr'
components:
  schemas: {}
  securitySchemes:
    Access Token:
      type: apiKey
      in: header
      name: Authorization
  links: {}
  callbacks: {}
security: []
