name: Build Preview Docker Image

on:
  push:
    branches:
      - dev

env:
  DOCKER_BUILDKIT: 1
  IMAGE_NAME: ghcr.io/tapie-kr/api:preview
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GH_USERNAME: ${{ secrets.GH_USERNAME }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        run: echo "SENTRY_AUTH_TOKEN=$SENTRY_AUTH_TOKEN" > .env
      
      - name: Login to GitHub Container Registry
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
        run: echo $GH_TOKEN | docker login ghcr.io -u $GH_USERNAME --password-stdin
      
      - name: Build Docker image
        env:
          DOCKER_BUILDKIT: ${{ env.DOCKER_BUILDKIT }}
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: docker build -t $IMAGE_NAME .
      
      - name: Push Docker image to GitHub Container Registry
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
        run: docker push $IMAGE_NAME
